homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 223
  unit_system: metric
  time_zone: America/Toronto
  customize: !include customize.yaml
  external_url: !secret external_url
  internal_url: !secret internal_url
########### !include Configuration #############
light: !include_dir_merge_list light/
sensor: !include_dir_merge_list sensor/
group: !include_dir_merge_named group/
# automation editor: !include automations.yaml
automation folder: !include_dir_merge_list automations/
# panel_iframe: !include_dir_merge_list panel_iframe/
shell_command: !include_dir_merge_named shell-commands/
binary_sensor: !include_dir_merge_list binary-sensor/
media_player: !include media_player.yaml
input_boolean: !include input_boolean.yaml
input_select: !include input_select.yaml
script: !include_dir_merge_named scripts/
switch: !include_dir_merge_list switch/
# packages: !include_dir_named packages
input_text: !include input_text.yaml
# input_slider: !include input_slider.yaml
scene: !include scenes.yaml
image_processing: !include image_processing.yaml
###############################################

#################### HTTP #####################
http:
  use_x_forwarded_for: true
  trusted_proxies: 192.168.0.17
##############################################
api:
breaking_changes:
############## Voice Assistant's ##############
alexa: !include alexa.yaml
homekit:
  ip_address: 192.168.0.19
  auto_start: False
  filter:
    include_domains:
      - climate
      - switch
      - light
      - camera
    include_entities:
      - cover.garage_door
    exclude_entities: !include homekit_exclude.yaml
  # filter:
  #   include_entities:
  #     - demo.demo
google_assistant:
  project_id: !secret project_id
  service_account: !include SERVICE_ACCOUNT.json
  exposed_domains:
    - switch
    - light
    - camera
  entity_config:
    script.going_to_bed:
      expose: true
    input_boolean.movie_time:
      expose: true
    cover.garage_door:
      expose: true
######################################
########## Basic Configuration ###########
updater:
discovery:
ffmpeg:
  ffmpeg_bin: /usr/bin/ffmpeg
frontend:
    themes: !include_dir_merge_named themes/
config:
map:
mobile_app:

camera: !include_dir_merge_list camera/
#### ZoneMinder ####
# zoneminder:
#   - host: 192.168.0.14:9080
#     username: !secret zmuser
#     password: !secret zmpw
####################

#### ESXi Stats #####
esxi_stats:
  host: 192.168.0.2
  username: !secret esxi_user
  password: !secret esxi_pw
#####################


######## Recorder ########
recorder:
  # purge_interval: 1
  purge_keep_days: 7
  db_url: !secret db_url
#########################

######## Cloudflare ########
cloudflare:
  email: !secret emailM
  api_key: !secret cfapi
  zone: !secret cfzone
  records:
    - !secret cfrecord
#########################


# Allows you to issue voice commands from the frontend in enabled browsers
conversation:
### Timer ###
timer:
  google_kitchen:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:
# Weather Prediction
weather:
  - platform: darksky
    api_key: !secret darkskyapi
  - platform: environment_canada
    forecast: hourly
  # - platform: openweathermap
  #   api_key: !secret owm_key


# Text to speech
tts:
  - platform: google_translate


# ring:
#   username: !secret emailring
#   password: !secret ring

notify:
  - platform: html5
    vapid_pub_key: !secret vappubkey
    vapid_prv_key: !secret vapprvkey
    vapid_email: !secret vapemail
zone: !include_dir_merge_list zones/

media_extractor:
######## Roku TV ########
roku:
  - host: 192.168.0.37
#########################
wemo:
  static:
    - 192.168.0.88
    - 192.168.0.89
    - 192.168.0.78
    - 192.168.0.77
    - 192.168.0.86
    - 192.168.0.87
    - 192.168.0.23
    - 192.168.0.95
cover:
  - platform: myq
    username: !secret myquser
    password: !secret myqpass
    type: chamberlain
logger:
  default: warn
  logs:
    homeassistant.components.mqtt.binary_sensor: critical
    homeassistant.loader: error
    homeassistant.components..switch.alexa_media: error
  # logs:
    # homeassistant.components.homekit: debug
    # pyhap: debug
nest:
  client_id: !secret id
  client_secret: !secret client
#
# life360:
#   accounts:
#     username: !secret life360_username
#     password: !secret life360_password
sonos:
  media_player:
    interface_addr: 192.168.0.19
    hosts: 192.168.0.125
system_health:
# speedtestdotnet:
#   scan_interval:
#     minutes: 30
#   monitored_conditions:
#     - ping
#     - download
#     - upload
# fastdotcom:
#   scan_interval:
#       minutes: 30
alexa_media:
  accounts:
    - email: !secret azemail
      password: !secret azpass
      url: amazon.com
# googlehome:
#   devices:
#     - host: '192.168.0.35'
#       device_types: 2
#       track_alarms: true
#       track_devices: false
stream:
tplink:
  discovery: false
  switch:
    - host: 192.168.0.109
    - host: 192.168.0.107
    - host: 192.168.0.135
    - host: 192.168.0.20
    - host: 192.168.0.21
########### InfluxDB ##########
influxdb:
  host: a0d7b954-influxdb
  port: 8086
  database: homeassistant
  username: !secret influxdb_user
  password: !secret influxdb_pw
  max_retries: 3
  default_measurement: state
###############################
