- platform: tplink
  host: 192.168.0.109
  scan_interval: 5
- platform: tplink
  host: 192.168.0.107
  scan_interval: 5
- platform: tplink
  host: 192.168.0.135
  scan_interval: 5
- platform: tplink
  host: 192.168.0.20
  scan_interval: 5
- platform: tplink
  host: 192.168.0.21
  scan_interval: 5
