- alias: 'Heat Warning TTS'
  trigger: 
    - platform: state 
      entity_id: 'sensor.weather_alerts'
      to: "HEAT WARNING IN EFFECT, Vaughan - Richmond Hill - Markham"
  action: 
    - service: script.say_sonos
      data_template:
        entity_id: media_player.main_floor
        message: "Heat Warning in effect in Richmond Hill"
- alias: 'Thunderstorm TTS Watch'
  trigger: 
    - platform: state 
      entity_id: 'sensor.weather_alerts'
      to: "SEVERE THUNDERSTORM WATCH IN EFFECT, Vaughan - Richmond Hill - Markham"
  action: 
    - service: script.say_alert
      data_template:
        entity_id: media_player.main_floor
        message: "SEVERE THUNDERSTORM WATCH IN EFFECT in Richmond Hill"
- alias: 'Thunderstorm TTS Warning'
  trigger: 
    - platform: state 
      entity_id: 'sensor.weather_alerts'
      to: "SEVERE THUNDERSTORM WARNING IN EFFECT, Vaughan - Richmond Hill - Markham"
  action: 
    - service: script.say_alert
      data_template:
        entity_id: media_player.main_floor
        message: "SEVERE THUNDERSTORM WARNING IN EFFECT in Richmond Hill"