- alias: 'Feed Dog'
  trigger: 
    platform: time
    at: '16:30:00'
  action: 
    - service: script.say_all
      data_template:
        entity_id: media_player.main_floor
        message: "Time to Feed the Dog!"
    - service: notify.mobile_app_mathesons_iphone_8_plus
      data_template:
        message: "Time to Feed the Dog!!!"
    - service: notify.html5_matheson_pc
      data_template:
        message: "Time to Feed the Dog!!!"