- alias: 'Home Assistant Boot'
  trigger:
    - platform: homeassistant
      event: start
  action:
    - service: notify.html5_matheson_pc
      data_template:
        message: "Home Assistant Started"
    - service: notify.mobile_app_mathesons_iphone_8_plus
      data_template:
        message: "Home Assistant Started"