- alias: 'kodi_on'
  hide_entity: True
  trigger:
    - platform: state
      entity_id: media_player.kodi
      from: 'idle'
      to: 'playing'
  action:
    - service: switch.turn_off
      data:
        entity_id: switch.family_room
- alias: 'kodi_paused'
  hide_entity: True
  trigger:
    - platform: state
      entity_id: media_player.kodi
      from: 'playing'
      to: 'paused'
  action:
    - service: switch.turn_on
      data:
        entity_id: switch.family_room
- alias: 'kodi_off'
  hide_entity: True
  trigger:
    - platform: state
      entity_id: media_player.kodi
      from: 'paused'
      to: 'idle'
  action:
    - service: switch.turn_on
      data:
        entity_id: switch.family_room
- alias: 'kodi_playing'
  hide_entity: True
  trigger:
    - platform: state
      entity_id: media_player.kodi
      from: 'paused'
      to: 'playing'
  action:
    - service: switch.turn_off
      data:
        entity_id: switch.family_room
- alias: 'Kodi_idle'
  hide_entity: True
  trigger:
    - platform: state
      entity_id: media_player.kodi
      from: 'playing'
      to: 'idle'
  action:
    - service: switch.turn_on
      data:
        entity_id: switch.family_room
- alias: 'ATV_on'
  hide_entity: True
  trigger:
    - platform: state
      entity_id: media_player.mathesons_apple_tv
      from: 'idle'
      to: 'playing'
  action:
    - service: switch.turn_off
      data:
        entity_id: switch.dining_room
- alias: 'ATV_paused'
  hide_entity: True
  trigger:
    - platform: state
      entity_id: media_player.mathesons_apple_tv
      from: 'playing'
      to: 'paused'
  action:
    - service: switch.turn_on
      data:
        entity_id: switch.dining_room
- alias: 'ATV_off'
  hide_entity: True
  trigger:
    - platform: state
      entity_id: media_player.mathesons_apple_tv
      from: 'paused'
      to: 'idle'
  action:
    - service: switch.turn_on
      data:
        entity_id: switch.dining_room
- alias: 'ATV_playing'
  hide_entity: True
  trigger:
    - platform: state
      entity_id: media_player.mathesons_apple_tv
      from: 'paused'
      to: 'playing'
  action:
    - service: switch.turn_off
      data:
        entity_id: switch.dining_room
- alias: 'ATV_idle'
  hide_entity: True
  trigger:
    - platform: state
      entity_id: media_player.mathesons_apple_tv
      from: 'playing'
      to: 'idle'
  action:
    - service: switch.turn_on
      data:
        entity_id: switch.dining_room