- alias: 'Motion Night'
  trigger:
    - platform: state
      entity_id: group.main_floor_motion
      to: 'on'
  condition:
    condition: and
    conditions:
      - condition: time
        before: '05:00:00'
      - condition: state
        entity_id: 'input_boolean.night'
        state: 'on'
      - condition: time
        after: '23:30:00'
  action:
    - service: homeassistant.turn_on
      data_template:
        entity_id: group.main_floor
    - service: script.night_tts
      data_template:
        message: 'There is motion Downstairs, is someone having a midnight snack'
        entity_id: media_player.master_bedroom_speaker
    - delay:
        minutes: 5
    - service: homeassistant.turn_off
      data_template:
        entity_id: group.main_floor



- alias: 'Midnight Snack'
  trigger:
    - platform: state
      entity_id: group.main_floor_motion
      to: 'on'
  condition:
    condition: and
    conditions:
      - condition: time
        after: '23:30:00'
        before: '05:00:00'
      - condition: state
        entity_id: 'input_boolean.night'
        state: 'on'
  action:
    - service: script.night_tts
      data_template:
        message: 'There is motion Downstairs, is someone having a midnight snack?'
        entity_id: media_player.master_bedroom_speaker


- alias: 'Motion Glenn'
  trigger:
    - platform: state
      entity_id: group.main_floor_motion
      to: 'on'
  condition:
    condition: and
    conditions:
      - condition: sun
        before: sunrise
      - condition: time
        # At least one of the following is required.
        after: '05:00:00'
      - condition: state
        entity_id: 'binary_sensor.workday_sensor'
        state: 'on'
  action:
    - service: homeassistant.turn_off
      data_template:
        entity_id: input_boolean.night
    # - delay: '00:00:03'
    - service: homeassistant.turn_on
      data_template:
        entity_id: group.main_floor