- alias: 'Sandy Home Outdoor'
  trigger:
    - platform: state
      entity_id: device_tracker.life360_sandy_steplock
      from: 'not_home'
      to: 'home'
  condition:
    condition: sun
    after: sunset
    offset: "-00:45:00"
  action:
    - service: script.turn_on
      data:
        entity_id: script.front_door_timer
- alias: 'Glenn Home Outdoor'
  trigger:
    - platform: state
      entity_id: device_tracker.life360_glenn_steplock
      from: 'not_home'
      to: 'home'
  condition:
    condition: sun
    after: sunset
    offset: "-00:45:00"
  action:
    - service: script.turn_on
      data:
        entity_id: script.front_door_timer
- alias: 'Matheson Home Outdoor'
  trigger:
    - platform: state
      entity_id: device_tracker.life360_matheson_steplock
      from: 'not_home'
      to: 'home'
  condition:
    condition: sun
    after: sunset
    offset: "-00:45:00"
  action:
    - service: script.turn_on
      data:
        entity_id: script.front_door_timer