- alias: 'Day Mode'
  trigger:
    - platform: state
      entity_id: input_boolean.night
      to: 'off'
  action:
    - service: homeassistant.turn_on
      data:
       entity_id: input_boolean.speech
    - service: automation.turn_on
      data:
        entity_id: automation.pot_lights_on_rain
    # - service: homeassistant.turn_off
    #   data:
    #     entity_id: input_boolean.night
    - service: homeassistant.turn_off
      data:
        entity_id: group.front_lighting
    - service: script.weather_alerts_reset