- alias: 'Glenn Home TTS'
  trigger:
    - platform: state
      entity_id: device_tracker.life360_glenn_steplock
      from: 'not_home'
      to: 'home'
  action:
    - service: script.say_home
      data_template:
        entity_id: media_player.main_floor
        message: "Glenn is Home"
- alias: 'Matheson Home TTS'
  trigger:
    - platform: state
      entity_id: device_tracker.life360_matheson_steplock
      from: 'not_home'
      to: 'home'
  action:
    - service: script.say_home
      data_template:
        entity_id: media_player.main_floor
        message: "Matheson is Home"
- alias: 'Sandy Home TTS'
  trigger:
    - platform: state
      entity_id: device_tracker.life360_sandy_steplock
      from: 'not_home'
      to: 'home'
  action:
    - service: script.say_home
      data_template:
        entity_id: media_player.main_floor
        message: "Sandy is Home"
- alias: 'Zack Home TTS'
  trigger:
    - platform: state
      entity_id: device_tracker.life360_zachary_steplock
      from: 'not_home'
      to: 'home'
  action:
    - service: script.say_sonos
      data_template:
        entity_id: media_player.main_floor
        message: "Zack is Home"