- alias: 'Pot Lights On Rain'
  trigger: 
    - platform: state
      entity_id: weather.richmond_hill
      to: 'Rainy'
    - platform: state
      entity_id: sensor.icon_code_2
      to: '19'
    - platform: state
      entity_id: sensor.icon_code_2
      to: '39'
    - platform: state
      entity_id: sensor.icon_code_2
      to: '13'
    - platform: state
      entity_id: sensor.icon_code_2
      to: '46'
    - platform: state
      entity_id: sensor.icon_code_2
      to: '47'
    # - platform: state 
    #   entity_id: sensor.dark_sky_summary
    #   to: 'Light Rain'
    # - platform: state 
    #   entity_id: sensor.dark_sky_summary
    #   to: 'Heavy Rain'
  action: 
    - service: script.say_sonos
      data_template:
        message: "The weather condition has changed to {{ states('sensor.condition_2') }}, so I have turned on the lights"
    - service: homeassistant.turn_on
      entity_id: group.main_floor