- alias: 'Sunset Main Floor'
  trigger:
    - platform: sun
      event: sunset
      offset: '-00:15:00'
  condition:
    - condition: state
      entity_id: input_select.home_status
      state: 'Home'
  action:
    - service: script.say_sonos
      data_template:
        message: "It's getting dark outside, so I have turned on the lights"
    - service: homeassistant.turn_on
      data:
        entity_id: group.main_floor

- alias: 'Sunset Outdoor Winter or Autumn'
  trigger:
    platform: sun
    event: sunset
    condition:
      condition: or
      conditions:
        - condition: state
          entity_id: sensor.season
          state: 'Winter'
        - condition: state
          entity_id: sensor.season
          state: 'Autumn'
  action:
    - service: script.say_sonos
      data_template:
        message: "The sun has set and now I have turned on the Outside Lights"
    - service: homeassistant.turn_on
      data:
        entity_id: group.front_lighting

- alias: 'Sunset Outdoor Not Winter'
  trigger:
    platform: sun
    event: sunset
  condition:
    condition: not
    conditions:
      - condition: state
        entity_id: sensor.season
        state: 'Winter'
      - condition: state
        entity_id: sensor.season
        state: 'Autumn'
  action:
    - service: script.say_sonos
      data_template:
        message: "The sun has set and now I have turned on the Outside Lights"
    - service: homeassistant.turn_on
      data:
        entity_id: switch.front_door
    - service: homeassistant.turn_off
      data:
        entity_id: switch.outdoor_landscaping

- alias: 'Sunrise Front Lighting Off'
  trigger:
    platform: sun
    event: sunrise
  action:
    - service: homeassistant.turn_off
      data:
        entity_id: group.front_lighting