- alias: 'Weather Warning Alert'
  trigger:
    - platform: state
      entity_id: sensor.warnings
  condition:
    - condition: template
      value_template: "{{ not is_state('sensor.warnings', '') }}"
  action:
    - service: script.say_alert
      data_template:
        message: "{{ states('sensor.warnings') }} in effect."
- alias: 'Weather Watches Alert'
  trigger:
    - platform: state
      entity_id: sensor.watches
  condition:
    - condition: template
      value_template: "{{ not is_state('sensor.warnings', '') }}"
  action:
    - service: script.say_alert
      data_template:
        message: "{{ states('sensor.watches') }} in effect."